### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'ibpr'

### ISSUE THREAD

**Issue by aknirala** [alessandrodepalma/expressive-losses#3]
When I run train.py to reproduce first MNIST results I get error as (line numbers would probably be incremented by 6-7 lines as I modified train.py due to my cluster constrains):

```
Traceback (most recent call last):
  File "/cnvrg/expressive-losses/train.py", line 353, in <module>
    main(args)
  File "/cnvrg/expressive-losses/train.py", line 325, in main
    train_or_test(model, model_ori, t, train_data, eps_scheduler, opt)
  File "/cnvrg/expressive-losses/train.py", line 162, in train_or_test
    if (not args.ibpr) and (not args.ccibp) and (not args.mtlibp) and (not args.sabr) and (not args.expibp):
AttributeError: 'Namespace' object has no attribute 'ibpr'
```

To run the code, I simply removed the flag ` (not args.ibpr) and`. Not sure if that was the right thing to do.

**Comment by alessandrodepalma** [comment]
Thanks for spotting this and sorry about that. The flag was inadvertently left in when cleaning the code, I now removed it: https://github.com/alessandrodepalma/expressive-losses/commit/3df64fa997e275605c331054499f36cc9f213187.
